name: Renovate

on:
  workflow_dispatch:
#on:
#  schedule:
#    - cron: '4 4 * * *'
#  workflow_dispatch:


jobs:
  renovate:
    permissions:
      # actions: read|write|none
      # checks: read|write|none
      contents: write
      # deployments: read|write|none
      # id-token: read|write|none
      issues: read
      # discussions: read|write|none
      # packages: read|write|none
      # pages: read|write|none
      pull-requests: write
      repository-projects: read
      # security-events: read|write|none
      statuses: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6
      - name: Renovate
        uses: renovatebot/github-action@v40.1.11
        with:
          configurationFile: renovate.json
          token: ${{ secrets.GITHUB_TOKEN }}
    env:
      LOG_LEVEL: 'debug'
