name: Renovate

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * 0'

jobs:
  renovate:
    permissions:
      contents: read
      issues: read
      pull-requests: write
      repository-projects: read
      statuses: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6
      - name: Renovate
        uses: renovatebot/github-action@v40.1.12
        with:
          configurationFile: renovate-config.json
          token: ${{ secrets.GITHUB_TOKEN }}
    env:
      LOG_LEVEL: 'debug'
