name: Renovate

on:
  workflow_dispatch:
#on:
#  schedule:
#    - cron: '4 4 * * *'
#  workflow_dispatch:


jobs:
  renovate:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.1.11
        with:
          #configurationFile: renovate-config.json
          token: ${{ secrets.GITHUB_TOKEN }}
    env:
      LOG_LEVEL: 'debug'
