name: Renovate

on: workflow_dispatch
#on:
#  schedule:
#    - cron: '4 4 * * *'
#  workflow_dispatch:


jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.1.11
        with:
          docker-cmd-file: .github/renovate-entrypoint.sh
          docker-user: root
          token: ${{ secrets.GITHUB_TOKEN }}
